name: Static Analysis

on:
  workflow_call:

jobs:
  static-check:
    name: Run Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Betterleaks
        uses: dortort/betterleaks-action@v0.1.0
        with:
          version: "v1.9.0"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run static analysis
        run: npx prek --all-files

      - name: Test Building Docs
        run: npm run docs
