#
# Run unit tests.
#
name: Test

on:
  workflow_call:

jobs:
  run-tests:
    name: Run Tests
    strategy:
      max-parallel: 4
      matrix:
        os:
          - "ubuntu-latest"
        node-version:
          - "18"
          - "20"
          - "22"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Set up Poppler on ubuntu
        run: sudo apt install -y poppler-utils

      - name: Install Node.js dependencies
        run: npm ci

      - name: Compilation
        run: npm run build

      - name: Test code
        run: npm run test
