name: Crontab

on:
  schedule:
  - cron: '23 0 * * *'

jobs:
  test_regressions:
    uses: mindee/mindee-api-nodejs/.github/workflows/_test-regressions.yml@main
    secrets: inherit
  test_code_samples:
    uses: mindee/mindee-api-nodejs/.github/workflows/_test-code-samples.yml@main
    secrets: inherit
