name: Documentation

on:
  release:
    types: [ published ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Generate docs
        run: |
          npm run docs-for-dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
