name: Test Code Samples
on:
  pull_request:
  schedule:
    - cron:  '0 23 * * *'
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "18"
          - "20"
          - "22"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build
        run: npm run build-for-dist

      - name: Tests sample code
        run: |
          ./tests/test_code_samples.sh ${{ secrets.MINDEE_ACCOUNT_SE_TESTS }} ${{ secrets.MINDEE_ENDPOINT_SE_TESTS }} ${{ secrets.MINDEE_API_KEY_SE_TESTS }}

